# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Sets user-defined palette
palette = "catppuccin_mocha"

# ! opt-in for individual modules (e.g., aws, docker, gcloud, nodejs, python)
# standalone format to get os glyph on ps1 line,
# prompt character below
format = """
[](bg:transparent fg:green)\
$os\
$username\
$hostname\
[](fg:green bg:overlay0)\
$time\
[ ](fg:overlay0 bg:blue)\
$directory\
[](fg:blue bg:yellow)\
$git_branch\
$git_status\
$git_commit\
$git_metrics\
[](fg:yellow bg:transparent)\
$aws\
$python\
$cmd_duration
$character
"""

# right_format = """
# """

[character]
format = "$symbol "
success_symbol = '[\$](green)'
error_symbol = '[\$](purple)'

[os]
format = "[$symbol]($style)"
style = "bg:green fg:mantle"
disabled = false

[os.symbols]
Linux = " "
Macos = " "
Mint = " "
Raspbian = " "
Redhat = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[username]
style_user = "bg:green fg:mantle"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[@$hostname ](bg:green fg:mantle)"
disabled = false

[time]
time_format = "%T" # Hour:Minute Format
format = "[ 󱑍 $time ](bg:overlay0 fg:yellow)"
disabled = false

[directory]
home_symbol = "󰋜 ~"
truncation_length = 25
truncation_symbol = "󰇘 "
truncate_to_repo = true
style = "fg:mantle bg:blue"
read_only = "󰍁"
read_only_style = "fg:base bg:blue"
format = '[  $path]($style)[ $read_only ]($read_only_style)'

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
style = "fg:base bg:yellow"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
style = "fg:surface0 bg:yellow"

[git_metrics]
format = "([ +$added]($added_style))([ -$deleted ]($deleted_style))"
added_style = "fg:surface1 bg:yellow"
deleted_style = "fg:red bg:yellow"
disabled = false

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold peach'
symbol = ' '

# [aws.region_aliases]
# ca-central-1 = ''

[aws.profile_aliases]
administrator-production-ready-serverless = 'admin-serverless'

### Disabled modules

[azure]
disabled = true

[battery]
disabled = true

[buf]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cmd_duration]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[container]
disabled = true

[crystal]
disabled = true

[custom]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[direnv]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[fennel]
disabled = true

[fossil_branch]
disabled = true

[fossil_metrics]
disabled = true

[gcloud]
disabled = true

[git_state]
disabled = true

[gleam]
disabled = true

[golang]
disabled = true

[gradle]
disabled = true

[guix_shell]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[hg_branch]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[line_break]
disabled = true

[localip]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[meson]
disabled = true

[nats]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[opa]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pijul_channel]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[quarto]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[rlang]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shell]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[solidity]
disabled = true

[spack]
disabled = true

[status]
disabled = true

[sudo]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[typst]
disabled = true

[vagrant]
disabled = true

[vcsh]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
transparent = "#00FFFFFF"

