import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

#decorations = "Buttonless"

opacity = 0.75
blur = true

#option_as_alt = "Both"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  { key = "Back",  mods = "Alt", chars= "\u001b\u007f" },
  { key = "Right", mods = "Super",  chars= "\u001bOF", mode= "AppCursor" },
  { key = "Left", mods = "Super",  chars= "\u001bOH", mode= "AppCursor" },
  { key = "Back", mods = "Super",  chars= "\u0015" }

]


[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 16

